### ISSUE TITLE
raise Exception('sth wrong with req')

### ISSUE THREAD

**Issue by huballo** [dPeS/pronto#1]
Witam,
Działa ta aplikacja jeszcze? Możesz bardziej rozwinąć readme do niej? Jak był nie wpisał cientdi i secret daje mi błąd autoryzacji. W jakiej formie trzeba to wpisać? Aplikację zarejestrować jako device?
Pozdrawiam

**Comment by dPeS** [comment]
tak appke zarejestrować jako DEVICE
faktycznie był błąd - zapomniałem o kodowaniu base64 które wykonałem ręcznie - poprawiłem kod i manual, spróbuj teraz proszę

**Comment by dPeS** [comment]
@huballo udało się może?

**Comment by huballo** [comment]
Przepraszam dopiero dzisiaj miałem czas zajrzeć do tego. Tak teraz działa. Dzięki

**Comment by dPeS** [comment]
zamykam wiec
